version: 2.1

orbs:
  maven : archmix/maven@2.0.0

workflows:
  version: 2
  build-deploy:
    jobs:
      - maven/build:
          context: Triady
      - maven/release:
          context: Triady
          requires:
            - maven/build
          filters:
            branches:
              only: master